### PR TITLE
Dockerise ecolex

### PR DESCRIPTION
**Pull request by anaion**
@alexef please review

### CODE REVIEW

**Comment by alexef** [comment]
compose looks really good, setup should probably work on a single machine.

Can you provide instruction (in README or different compose file(s)) on how to set it up on four docker hosts, the same as in production?

- 1, 2, 3: zk and solr
- 4: zk, solr and django 

What volumes does `makuk66/docker-solr` have?

**Comment by anaion** [comment]
The production environment will be considerably different. First of all, you need to decide whether a single ZK node will be deployed, or an ensemble (a ZK cluster). This choice will impact the docker-compose files and the Solr configuration.

The image doesn't attach any volumes at the moment.

**Comment by alexef** [comment]
Can you please make a proposal for the topology created on: http://redmine.eaudeweb.ro/issues/3094 ?

**Comment by anaion** [comment]
Given the fact that we agreed to run ZK externally, I don't think the production setup should be a single node deployment. My proposal would be:
- 3 node ZK ensemble (this will be resilient to a one node failure)
- 4 solr nodes, ideally not co-located with the ZK instances

**Comment by iuliachiriac** [comment]
@alexef please review

**Pull request merged**
